#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://${DB_HOST:vprodb}:${DB_PORT:3306}/${DB_NAME:accounts}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=${DB_USERNAME:root}
jdbc.password=${DB_PASSWORD:vprodbpass}

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=${MEMCACHED_ACTIVE_HOST:vprocache01}
memcached.active.port=${MEMCACHED_ACTIVE_PORT:11211}
#For StandBy Host
memcached.standBy.host=${MEMCACHED_STANDBY_HOST:127.0.0.2}
memcached.standBy.port=${MEMCACHED_STANDBY_PORT:11211}

#RabbitMq Configuration
rabbitmq.address=${RABBITMQ_HOST:vpromq01}
rabbitmq.port=${RABBITMQ_PORT:5672}
rabbitmq.username=${RABBITMQ_USERNAME:guest}
rabbitmq.password=${RABBITMQ_PASSWORD:guest}

#Elasticesearch Configuration
elasticsearch.host=${ELASTICSEARCH_HOST:localhost}
elasticsearch.port=${ELASTICSEARCH_PORT:9300}
elasticsearch.cluster=${ELASTICSEARCH_CLUSTER:vprofile}
elasticsearch.node=${ELASTICSEARCH_NODE:vprofilenode}


spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:128KB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:128KB}

logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:DEBUG}


# application.properties
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin_vp}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin_vp}
spring.security.user.roles=${SPRING_SECURITY_USER_ROLES:ADMIN}


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#logging.level.root=${LOGGING_LEVEL_ROOT:OFF}
#logging.level.org.springframework.web=OFF
#spring.main.banner-mode=OFF

# Hibernate SQL Queries
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:false}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE:OFF}
logging.level.org.hibernate.type=OFF


# Debug Logging for SecurityServiceImpl
logging.level.com.visualpathit.account.service.SecurityServiceImpl=OFF


